"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WindSong } from "next/font/google";
import "./globals.css";
import Header from './components/header'
import Footer from './components/footer'
import '../lib/i18n';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const windSong = WindSong({
  variable: "--font-windsong",
  weight: ["400", "500"], 
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${windSong.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}