import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WindSong } from "next/font/google";
import "./globals.css";
import Footer from './components/footer'
import Header from './components/header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const windSong = WindSong({
  variable: "--font-windsong",
  weight: ["400", "500"], // You can pick weights you want
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${windSong.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
